<?php 
echo $this->getHelloWorldTxt();
echo '<br />';
 $block->getCatalogSession()->setMyName('Trung');
 echo "<h1 class='oknuon1'>".$block->getCatalogSession()->getMyName()."</h1>" ; // output: Mageplaza
echo '<br />';
 $block->getCheckoutSession()->setTestData('Test session and overriver layout and apply css for this situation ');
 echo "<h2 class='oknuon2'>".$block->getCheckoutSession()->getTestData()."</h2>"; // output: Hello World
echo '<br />';
 $block->getCheckoutSession()->setTestHello('Test Hello Value');
 echo "<h3 class='oknuon3'>".$block->getCheckoutSession()->getTestHello()."</h3>"; // output: Test Hello Value

?>
